export const PERMISSIONS = {
  BILLING: {
    MANAGE: "BILLING_MANAGE",
  },
  CORPORATE: {
    CREATE: "CORPORATE_CREATE",
    READ: "CORPORATE_READ",
    ASSIGN: "CORPORATE_ASSIGN",
  },
  ISSUE: {
    ASSIGN: "ISSUE_ASSIGN",
    CREATE: "ISSUE_CREATE",
  },
  PROJECT: {
    CREATE: "PROJECT_CREATE",
    READ: "PROJECT_READ",
    UPDATE: "PROJECT_UPDATE",
    DELETE: "PROJECT_DELETE",
  },
  REPORT: {
    VIEW: "REPORT_VIEW",
  },
  TASK: {
    CREATE: "TASK_CREATE",
    READ: "TASK_READ",
    UPDATE: "TASK_UPDATE",
    ASSIGN: "TASK_ASSIGN",
    APPROVE: "TASK_APPROVE",
  },
  USER: {
    READ: "USER_READ",
  },
};
